server:
  port: 8082
  servlet:
    context-path: /orgmanager
  ssl:
    enabled: true
    key-store: classpath:keystore-service2.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: service2

spring:
  application:
    name: organization-manager

# URL первого сервиса
service1:
  url: https://localhost:8081/api/v1/organizations
  ssl:
    trust-all: true  # Для self-signed сертификатов

# Настройки логирования
logging:
  level:
    com.example: DEBUG
    org.springframework.web: INFO